version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    rebase-strategy: auto
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: weekly