name: Build and deploy
env:
  SURGE_TOKEN_EXISTS: ${{ secrets.SURGE_TOKEN }}
on:
  push:
  pull_request:
jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
  deployRelease:
    if: ${{ github.ref == 'refs/heads/release' }}
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm install -g surge
    - name: Deploy
      if:  env.SURGE_TOKEN_EXISTS != ''
      run: surge ./build ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
  deployTest:
    if: ${{ github.ref != 'refs/heads/release' }}
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm install -g surge
    - name: Deploy
      if:  env.SURGE_TOKEN_EXISTS != ''
      run: surge ./build ${{ secrets.TEST_SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
