name: build test deploy

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
    - run: npm install -g surge
    - name: Test Deployment
      if: github.ref != 'refs/heads/main'
      run: surge ./build ${{ secrets.TEST_SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
    - name: Release Deployment
      if: github.ref == 'refs/heads/main'
      run: surge ./build ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
